---
- name: Configure logging
  hosts: nxos
  gather_facts: False

  vars:
    my_logging_config:
      - logging server 10.203.12.101 6 port 11001 use-vrf management
      - logging origin-id hostname

  tasks:
    - name: Configure syslog
      nxos_config:
        lines: "{{ my_logging_config }}"
        save_when: changed

