---
- name: Configure links between NXOS1 and NXOS2
  hosts: nxos1:nxos2 
  gather_facts: False
  tasks:

    - name: Enable LACP feature
      nxos_feature:
        feature: lacp
        state: enabled

    - name: Create LACP port-channel for links
      nxos_linkagg:
        group: "1"
        mode: active
        members:
          - Ethernet1/1
          - Ethernet1/2

    - name: Configure 801.1q trunk on port-channel
      nxos_l2_interface:
        name: port-channel1
        mode: trunk
        trunk_vlans: "1"

- name: Configure links between NXOS3 and NXOS4
  hosts: nxos3:nxos4
  gather_facts: False
  tasks:

    - name: Configure 802.1q on links
      nxos_l2_interface:
        name: Ethernet1/1
        mode: trunk
        trunk_vlans: "1"

- name: Save config
  hosts: nxos1:nxos2:nxos3:nxos4
  gather_facts: False
  tasks:

    - name: Save config
      nxos_config:
        save_when: modified
