---
- hosts: all
  gather_facts: no
  tasks:
  - name: Set authorized keys taken from url
    ansible.posix.authorized_key:
      user: arne
      state: absent
      key: https://ao-test.net/keys/arne.keys
